//
// Created by Nikita Kruk on 2019-03-05.
//

#ifndef SPC2PARTICLEFLUIDMOVIE_DEFINITIONS_HPP
#define SPC2PARTICLEFLUIDMOVIE_DEFINITIONS_HPP

typedef float Real;

#endif //SPC2PARTICLEFLUIDMOVIE_DEFINITIONS_HPP
